server:
  port: 8081

spring:
  application:
    name: aipe-backend
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/aipe_metadata?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: astock_root
      driver-class-name: com.mysql.cj.jdbc.Driver
    clickhouse:
      url: jdbc:clickhouse://localhost:8123/metric_observation
      username: default
      password: pamirs@123
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
