server:
  port: 8085

spring:
  application:
    name: aipe-timeline
clickhouse:
  url: http://124.223.220.245:8123
  user: default
  password: pamirs@123

# 日志
logging:
  level:
    com.aipe.timeline: DEBUG
    com.aipe.timeline.infrastructure: DEBUG
