server:
  port: 8082

spring:
  application:
    name: aipe-resource
  datasource:
    mysql:
      url: jdbc:mysql://124.223.220.245:3306/aipe_metadata?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: astock_root
      driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.aipe.resource.infrastructure.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_UUID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志
logging:
  level:
    com.aipe.resource: DEBUG
    com.aipe.resource.infrastructure.mapper: DEBUG
