server:
  port: 8080

spring:
  application:
    name: aipe-config-manager
  datasource:
    mysql:
      url: jdbc:mysql://124.223.220.245:3306/aipe_metadata?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: astock_root
      driver-class-name: com.mysql.cj.jdbc.Driver
    clickhouse:
      url: jdbc:clickhouse://124.223.220.245:8123/metric_observation
      username: default
      password: pamirs@123
      driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

aipe:
  config:
    heartbeat-timeout-seconds: 90
    heartbeat-check-interval-seconds: 30
